#include "mainwindow.h"
#include "ui_mainwindow.h"

//-------------Constructor----------------
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    dataManager = new DataManager(this);
    apiManager = new APIManager(dataManager);

    //TBD: KEY autogenerated on first opening and gets loaded via File (with second encryption
    encryptionHelper = new EncryptionHelper("End.T9@c;b!keLM");
    SetAPIKeyWindow = new SetAPIKey(dataManager,encryptionHelper, this);
}

//-------------Destructor----------------
MainWindow::~MainWindow()
{
    delete SetAPIKeyWindow;
    delete dataManager;
    delete apiManager;
    delete encryptionHelper;
    delete ui;
}

//Public Slots
void MainWindow::updateApiKey(const QString &newKey)
{

}

//Private Slots
void MainWindow::on_actionAPI_Key_triggered()
{
    //Opens teh Set APIKEY window
    SetAPIKeyWindow->setModal(true);
    SetAPIKeyWindow->exec();
}
